# GLOBAL SETTINGS
cname: gnl.yourwebvisual.com
allow_robots: false

# META
title: Gilshenan & Luton
title_homepage: Gilshenan & Luton - Brisbane's Criminal and Misconduct Lawyers
company: Gilshenan & Luton
description:

# DEVELOPER
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/gnl-0719
github_repo_name: gnl-0719
jekyll_version: 3.8.5

offices:
  aus:
    - city: All
      phone: 07 3361 0222
      fax: 617 3361 0201
      email: gn@gnl.com.au

  qld:
    - city: Brisbane
      email: gn@gnl.com.au
      phone: 07 3361 0222
      fax: 07 3361 0201
      address: Level 9,<br> 15 Adelaide Street<br> Brisbane<br> Qld 4000
      po_box: PO Box 12215<br> George Street Post Shop<br> Brisbane Qld 4003
      head_office: true

# GOOGLE
google_analytics: #UA-XXXXXXXX-X

# AUTHOR
author:
  title: Much Media
  url: https://www.muchmedia.com.au
  logo: /assets/img/ui/much-media-logo.svg
  description: Website by Much Media